package sharpi.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new API_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new CommandList_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new ContentType_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Input_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new JsonBody_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Output_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Route_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new XmlBody_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }



  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x98176b5e4bf7defL), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x98176b5e4c02c9cL), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b0617036L), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b0616785L), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b06168d7L), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b06167c5L), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b060e3ffL), MetaIdFactory.conceptId(0xacd9ee62a9d3435fL, 0xae26adca7e0b5a64L, 0x4a536579b061698dL)).seal();
}
